# ===----------------------------------------------------------------------=== #
# Nabla 2026
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------=== #

from .base import (
    BinaryOperation,
    AxisOp,
    ShapeOp,
    Operation,
    ReduceOperation,
    UnaryOperation,
    CreationOperation,
)
from .utils import (
    _get_tensor_hash,
    _make_hashable,
    _clear_hashable_cache,
    ensure_tensor,
    call_custom_kernel,
)
from .binary import (
    add,
    div,
    matmul,
    mul,
    sub,
    mod,
    pow,
    outer,
)
from .communication import (
    CollectiveOperation,
    all_gather,
    all_reduce,
    all_to_all,
    distributed_broadcast,
    ppermute,
    reduce_scatter,
    reshard,
    shard,
    to_device,
    transfer_to,
    cpu,
    gpu,
    accelerator,
)
from .comparison import (
    equal,
    greater,
    greater_equal,
    less,
    less_equal,
    not_equal,
    logical_xor,
)
from .control_flow import cond, scan, where, while_loop
from .creation import (
    arange,
    constant,
    full,
    gaussian,
    hann_window,
    normal,
    ones,
    uniform,
    zeros,
    zeros_like,
    ones_like,
    full_like,
    triu,
    tril,
)
from .multi_output import (
    chunk,
    minmax,
    split,
    unbind,
)
from .reduction import (
    mean,
    reduce_max,
    reduce_min,
    reduce_sum,
    argmax,
    argmin,
    cumsum,
)
from .unary import (
    abs,
    exp,
    log,
    neg,
    relu,
    sigmoid,
    softmax,
    sqrt,
    tanh,
    acos,
    atanh,
    cos,
    erf,
    floor,
    is_inf,
    is_nan,
    log1p,
    rsqrt,
    silu,
    sin,
    trunc,
    gelu,
    round,
    cast,
    logsoftmax,
)
from .view import (
    broadcast_to,
    concatenate,
    gather,
    reshape,
    scatter,
    slice_tensor,
    slice_update,
    squeeze,
    stack,
    swap_axes,
    unsqueeze,
    flip,
    permute,
    flatten,
    rebind,
    pad,
    as_interleaved_complex,
    view_as_real_interleaved,
)

# Aliases for base classes
UnaryOp = UnaryOperation
BinaryOp = BinaryOperation
ReduceOp = ReduceOperation
CollectiveOp = CollectiveOperation
CreationOp = CreationOperation


__all__ = [
    "Operation",
    "BinaryOperation",
    "UnaryOperation",
    "ReduceOperation",
    "ShapeOp",
    "AxisOp",
    "CollectiveOperation",
    "UnaryOp",
    "BinaryOp",
    "ReduceOp",
    "CollectiveOp",
    "CreationOp",
    "CreationOperation",
    "ensure_tensor",
    "add",
    "mul",
    "sub",
    "div",
    "matmul",
    "mod",
    "pow",
    "outer",
    "relu",
    "sigmoid",
    "tanh",
    "exp",
    "neg",
    "abs",
    "log",
    "sqrt",
    "softmax",
    "logsoftmax",
    "acos",
    "atanh",
    "cos",
    "erf",
    "floor",
    "is_inf",
    "is_nan",
    "log1p",
    "rsqrt",
    "silu",
    "sin",
    "trunc",
    "gelu",
    "round",
    "cast",
    "constant",
    "full",
    "zeros",
    "ones",
    "zeros_like",
    "ones_like",
    "full_like",
    "arange",
    "uniform",
    "gaussian",
    "hann_window",
    "normal",
    "triu",
    "tril",
    "equal",
    "not_equal",
    "greater",
    "greater_equal",
    "less",
    "less_equal",
    "logical_xor",
    "where",
    "cond",
    "while_loop",
    "scan",
    "reduce_sum",
    "mean",
    "reduce_max",
    "reduce_min",
    "argmax",
    "argmin",
    "cumsum",
    "unsqueeze",
    "squeeze",
    "swap_axes",
    "flip",
    "permute",
    "broadcast_to",
    "reshape",
    "flatten",
    "rebind",
    "pad",
    "as_interleaved_complex",
    "view_as_real_interleaved",
    "slice_tensor",
    "gather",
    "scatter",
    "slice_update",
    "stack",
    "concatenate",
    "minmax",
    "split",
    "chunk",
    "unbind",
    "shard",
    "all_gather",
    "all_reduce",
    "all_to_all",
    "ppermute",
    "reduce_scatter",
    "reshard",
    "distributed_broadcast",
    "to_device",
    "transfer_to",
    "cpu",
    "gpu",
    "accelerator",
    "call_custom_kernel",
]
