name: Build and Deploy Documentation (Lightweight)

on:
  push:
    branches:
      - main
      - nabla-python
  pull_request:
    branches:
      - main
      - nabla-python
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install documentation dependencies only
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      - name: Create minimal nabla stub
        run: |
          mkdir -p /tmp/nabla_stub/nabla
          cat > /tmp/nabla_stub/nabla/__init__.py << 'EOF'
          """
          Nabla stub for documentation building
          
          This is a minimal stub that allows documentation to be built without
          installing the full nabla package with all its dependencies.
          """
          # For numpy compatibility
          import numpy as np
          
          # Create dummy classes and functions for documentation
          class Array:
              """Array class for nabla."""
              def __init__(self, *args, **kwargs):
                  pass
                  
              def numpy(self):
                  """Convert to numpy array."""
                  return np.array([])
              
          def array(*args, **kwargs):
              """Create an array."""
              return Array()
              
          def arange(*args, **kwargs):
              """Create an array with evenly spaced values."""
              return Array()
              
          def sin(x):
              """Compute the sine of x."""
              return Array()
              
          def cos(x):
              """Compute the cosine of x."""
              return Array()
              
          def zeros(*args, **kwargs):
              """Create an array of zeros."""
              return Array()
              
          def ones(*args, **kwargs):
              """Create an array of ones."""
              return Array()

          def random(*args, **kwargs):
              """Create an array of random values."""
              return Array()
              
          def exp(*args, **kwargs):
              """Compute the exponential of x."""
              return Array()

          def log(*args, **kwargs):
              """Compute the natural logarithm of x."""
              return Array()

          # Add submodules
          class linalg:
              @staticmethod
              def norm(*args, **kwargs):
                  """Compute the norm of x."""
                  return Array()
          EOF
          
          cat > /tmp/nabla_stub/setup.py << 'EOF'
          from setuptools import setup, find_packages
          
          setup(
              name="nabla_ml",
              version="0.0.1",
              packages=find_packages(),
          )
          EOF
          
          cd /tmp/nabla_stub
          pip install -e .
          
      - name: Build documentation
        run: |
          cd docs
          # Try to build with gallery first, but if it fails, build without executing examples
          sphinx-build -b html . _build/html || sphinx-build -b html -D plot_gallery=0 . _build/html
          # Ensure .nojekyll file exists in the output directory
          touch _build/html/.nojekyll
          
      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/nabla-python' || github.event_name == 'workflow_dispatch'
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/nabla-python' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/_build/html'
          
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/nabla-python' || github.event_name == 'workflow_dispatch'
        id: deployment
        uses: actions/deploy-pages@v4
